# Generated by Django 5.2.7 on 2025-10-17 16:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premise_name', models.CharField(max_length=200)),
                ('lift_identifier', models.CharField(max_length=100, unique=True)),
                ('contractor_contact', models.CharField(blank=True, max_length=200)),
                ('jkr_pic_contact', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Detected', 'Detected'), ('Attended', 'Attended'), ('Pending Review', 'Pending Review'), ('Correction Required', 'Correction Required'), ('Resolved', 'Resolved')], default='Detected', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('time_attended', models.DateTimeField(blank=True, null=True)),
                ('time_resolved', models.DateTimeField(blank=True, null=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('report_due_date', models.DateTimeField(blank=True, null=True)),
                ('report_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('report_acknowledged_by_jkr', models.BooleanField(default=False)),
                ('report_requires_correction', models.BooleanField(default=False)),
                ('symptom', models.TextField(blank=True)),
                ('direct_cause', models.TextField(blank=True)),
                ('rc_method', models.TextField(blank=True, verbose_name='Root Cause: Method')),
                ('rc_man', models.TextField(blank=True, verbose_name='Root Cause: Man')),
                ('rc_material', models.TextField(blank=True, verbose_name='Root Cause: Material')),
                ('rc_machine', models.TextField(blank=True, verbose_name='Root Cause: Machine')),
                ('rc_proof', models.FileField(blank=True, null=True, upload_to='proofs/', verbose_name='Root Cause Proof')),
                ('corrective_action', models.TextField(blank=True)),
                ('corrective_action_proof', models.FileField(blank=True, null=True, upload_to='proofs/', verbose_name='Corrective Action Proof')),
                ('permanent_action', models.TextField(blank=True)),
                ('permanent_action_proof', models.FileField(blank=True, null=True, upload_to='proofs/', verbose_name='Permanent Action Proof')),
                ('contractor_acknowledgement', models.BooleanField(default=False)),
                ('lift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='lifts.lift')),
            ],
        ),
    ]
