# Generated by Django 5.2.7 on 2025-10-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifts', '0003_contractor_lift_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('Detected', 'Detected'), ('Attended', 'Attended'), ('Pending Review', 'Pending Review'), ('Correction Required', 'Correction Required'), ('Report Submitted', 'Report Submitted'), ('Resolved', 'Resolved')], default='Detected', max_length=20),
        ),
    ]
