# Generated by Django 5.2.7 on 2026-08-30 06:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifts', '0005_contractor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(default='device', max_length=20)),
                ('feature_p1', models.FloatField(default=0)),
                ('feature_p2', models.FloatField(default=0)),
                ('feature_p3', models.FloatField(default=0)),
                ('feature_s1', models.FloatField(default=0)),
                ('feature_s2', models.FloatField(default=0)),
                ('feature_s3', models.FloatField(default=0)),
                ('vibration', models.FloatField(default=0)),
                ('vertical_acceleration_mps2', models.FloatField(default=0)),
                ('acoustic_db', models.FloatField(default=0)),
                ('prediction', models.CharField(blank=True, max_length=80)),
                ('confidence', models.FloatField(default=0)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trigger_readings', to='lifts.incident')),
                ('lift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='lifts.lift')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lift', '-created_at'], name='lifts_senso_lift_id_46c586_idx')],
            },
        ),
    ]
